import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/common/footer/_footer";
import Navbar from "@/components/common/navbar/_navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex min-h-screen flex-col`}>
        <Navbar />
        <main className="flex grow flex-col">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
